name: samplefunctionapi_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    #- name: Install Swagger DLLs
    #  run: dotnet tool install --version 5.6.2 Swashbuckle.AspNetCore.Cli
    #- name: Swagger 
    #  run: dotnet swagger tofile --output swagger.json SampleFunctionAPI/bin/Release/netcoreapp3.1/SampleFunctionAPI.dll v1
    #- name: Run Spectral
    #  uses: stoplightio/spectral-action@v0.7.0
    #  with:
    #    file_glob: './swagger.json'
    - name: Publish
      run: dotnet publish --no-build -c Release -o dotnetcorefuncapp 
    - name: Zip
      uses: thedoctor0/zip-release@master
      with: 
        filename: dotnetcorefuncapp.zip
        directory: 'dotnetcorefuncapp' 
    - name: Display structure of downloaded files
      run: ls -R
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dotnetcorefuncapp
        path: |
            path/dotnetcorefuncapp/
            path/APIMPolicy/

  deploy_to_DEV:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment:
      name: DEV

    needs: [build]

    steps:
    - name: download sampleapi
      uses: actions/download-artifact@v2
      with:
        name: dotnetcorefuncapp
    - name: Display structure of downloaded files
      run: ls -R
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: samplefunctionapi-bc01
        package: './dotnetcorefuncapp/dotnetcorefuncapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    # az ad sp create-for-rbac --name "github-AzureSponsorship-3e2bea16-63ed-4349-9b9c-fe2f91f8e3d4" --sdk-auth --role contributor --scopes /subscriptions/3e2bea16-63ed-4349-9b9c-fe2f91f8e3d4
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    # APIM - Create the Versioned API before running the deployment    
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $ApiMgmtContext = New-AzApiManagementContext -ResourceGroupName "Samples" -ServiceName "samplebc"
          $Tags = 'key', 'function', 'auto'
          New-AzApiManagementNamedValue -Context $ApiMgmtContext -NamedValueId "samplefunctionapi-bc01-key" -Name "samplefunctionapi-bc01-key" -Value ${{secrets.SAMPLEFUNCTIONAPI_BC01_KEY}} -Secret -Tags $Tags
          $credential = New-AzApiManagementBackendCredential -Header "x-functions-key" @{"x-functions-key" = "samplefunctionapi-bc01-key"}
          New-AzApiManagementBackend -Context  $ApiMgmtContext -BackendId samplefunctionapi-bc01 -ResourceId "/subscriptions/3e2bea16-63ed-4349-9b9c-fe2f91f8e3d4/resourceGroups/Samples/providers/Microsoft.Web/sites/samplefunctionapi-bc01" -Url 'https://samplefunctionapi-bc01.azurewebsites.net/api' -Protocol http -Title "samplefunctionapi-bc01" -SkipCertificateChainValidation $true -Credential $credential -Description "samplefunctionapi-bc01"
          Set-AzApiManagementPolicy -Context $ApiMgmtContext -ApiId "sample-function-api" -PolicyFilePath './dotnetcorefuncapp/BackendServicePolicy.xml'
          $newRevision= ${{ github.run_number }}
          $revision = New-AzApiManagementApiRevision -Context $ApiMgmtContext -ApiId "sample-function-api" -ApiRevision "$newRevision" -ServiceUrl https://samplefunctionapi-bc01.azurewebsites.net
          Import-AzApiManagementApi -Context $ApiMgmtContext -SpecificationFormat OpenApi -SpecificationUrl https://samplefunctionapi-bc01.azurewebsites.net/api/swagger/json -ApiId "sample-function-api" -ApiRevision $revision.APIRevision -Path samplefuncapi -ServiceUrl https://samplefunctionapi-bc01.azurewebsites.net
        azPSVersion: '3.1.0'
